// Starter catalogue — pure data, no Firebase imports so it can be reused by both
// the web app (src/db.js) and the standalone migration script (scripts/migrate.mjs).
export const SEED = [
  { name: 'Momcozy S9 Pro (Simple)', cat: 'Tire-laits', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Momcozy S9 Pro (Lot de 2)', cat: 'Tire-laits', price: 0, cost: 0, qty: 23, threshold: 5 },
  { name: 'Momcozy S12 Pro (Simple)', cat: 'Tire-laits', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Momcozy S12 Pro (Lot de 2)', cat: 'Tire-laits', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Momcozy M5 Tire-lait Mains Libres (Simple)', cat: 'Tire-laits', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Momcozy M5 Tire-lait Mains Libres (Lot de 2)', cat: 'Tire-laits', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Momcozy Mobile Style™ M6 (Simple)', cat: 'Tire-laits', price: 0, cost: 0, qty: 61, threshold: 10 },
  { name: 'Momcozy Mobile Style™ M6 (Lot de 2)', cat: 'Tire-laits', price: 0, cost: 0, qty: 32, threshold: 10 },
  { name: 'Momcozy Mobile Flow™ M9 (Simple)', cat: 'Tire-laits', price: 0, cost: 0, qty: 33, threshold: 10 },
  { name: 'Momcozy Mobile Flow™ M9 (Lot de 2)', cat: 'Tire-laits', price: 0, cost: 0, qty: 33, threshold: 10 },
  { name: 'Momcozy V1 Pro – Tire-lait Électrique Portable', cat: 'Tire-laits', price: 0, cost: 0, qty: 1, threshold: 5 },
  { name: 'Momcozy V2 Pro – Tire-Lait Électrique Mains Libres', cat: 'Tire-laits', price: 0, cost: 0, qty: 11, threshold: 5 },
  { name: 'Lot de 50 Sacs de Conservation de Lait Maternel', cat: 'Accessoires', price: 0, cost: 0, qty: 62, threshold: 20 },
  { name: 'Sac de 8', cat: 'Accessoires', price: 0, cost: 0, qty: 367, threshold: 30 },
  { name: 'Coussin Rose', cat: 'Sommeil & Confort', price: 0, cost: 0, qty: 22, threshold: 5 },
  { name: 'Coussin Safari', cat: 'Sommeil & Confort', price: 0, cost: 0, qty: 19, threshold: 5 },
  { name: 'Coussin Citron', cat: 'Sommeil & Confort', price: 0, cost: 0, qty: 53, threshold: 5 },
  { name: 'Momcozy DreamLight 2 en 1 – Machine à Sons & Veilleuse', cat: 'Sommeil & Confort', price: 0, cost: 0, qty: 113, threshold: 10 },
  { name: 'Momcozy – Machine à Bruit Blanc & Veilleuse Bluetooth', cat: 'Sommeil & Confort', price: 0, cost: 0, qty: 49, threshold: 10 },
  { name: 'Momcozy – Chauffe-Lingettes & Veilleuse Intégrée', cat: 'Sommeil & Confort', price: 0, cost: 0, qty: 53, threshold: 10 },
  { name: 'Momcozy Baby Monitor 2-en-1 BM04', cat: 'Santé bébé', price: 0, cost: 0, qty: 10, threshold: 5 },
  { name: "Purificateur d'Air Chambre Bébé", cat: 'Santé bébé', price: 0, cost: 0, qty: 6, threshold: 5 },
  { name: 'Aspirateur Nasal Électrique Momcozy pour Bébé', cat: 'Santé bébé', price: 0, cost: 0, qty: 32, threshold: 10 },
  { name: 'Aspirateur Nasal Bébé 2-en-1 Momcozy avec Spray', cat: 'Santé bébé', price: 0, cost: 0, qty: 30, threshold: 10 },
  { name: 'Thermomètre Infrarouge Sans Contact Momcozy', cat: 'Santé bébé', price: 0, cost: 0, qty: 42, threshold: 10 },
  { name: 'Momcozy Chauffe-Biberon Stérilisateur Intelligent 6-en-1', cat: 'Repas bébé', price: 0, cost: 0, qty: 8, threshold: 5 },
  { name: 'Chauffe-Biberon Portable Sans Fil Momcozy', cat: 'Repas bébé', price: 0, cost: 0, qty: 2, threshold: 5 },
  { name: 'Stérilisateur & Sèche-Biberons 4-en-1 Momcozy', cat: 'Repas bébé', price: 0, cost: 0, qty: 103, threshold: 10 },
  { name: 'Momcozy Refroidisseur de Lait Maternel Portable 24h', cat: 'Repas bébé', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Ceinture Post-Partum Ergowrap – Taille M', cat: 'Post-partum', price: 0, cost: 0, qty: 2, threshold: 5 },
  { name: 'Ceinture Ventrale CozySupport – Taille L', cat: 'Post-partum', price: 0, cost: 0, qty: 2, threshold: 5 },
  { name: 'Crème Anti-Vergetures VERGESTOP', cat: 'Post-partum', price: 0, cost: 0, qty: 22, threshold: 10 },
  { name: 'Momcozy – Coussin de Grossesse & Allaitement', cat: 'Allaitement', price: 0, cost: 0, qty: 0, threshold: 5 },
  { name: 'Momcozy – Masseur de lactation chauffant 2-en-1', cat: 'Allaitement', price: 0, cost: 0, qty: 79, threshold: 10 },
  { name: 'Crème Mamelons Allaitement Soranos', cat: 'Allaitement', price: 0, cost: 0, qty: 27, threshold: 10 },
]
